// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKJdlMQVBFG8BTFBIH5istPEbTtLryEWA',
    appId: '1:942388891595:web:88e44bca58c2f6ea88304e',
    messagingSenderId: '942388891595',
    projectId: 'radar-grid-15e35',
    authDomain: 'radar-grid-15e35.firebaseapp.com',
    storageBucket: 'radar-grid-15e35.firebasestorage.app',
    measurementId: 'G-FQSNYP6SY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2yGi0-6fvCmXzqw58QCvVo6W5eRYIVQg',
    appId: '1:942388891595:android:747f13332c23b83c88304e',
    messagingSenderId: '942388891595',
    projectId: 'radar-grid-15e35',
    storageBucket: 'radar-grid-15e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2GxsmvuL1zzGu2Wc0uYBRZOD6CduOCx8',
    appId: '1:942388891595:ios:af85919962a4cdc788304e',
    messagingSenderId: '942388891595',
    projectId: 'radar-grid-15e35',
    storageBucket: 'radar-grid-15e35.firebasestorage.app',
    iosBundleId: 'com.example.theRadarGrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2GxsmvuL1zzGu2Wc0uYBRZOD6CduOCx8',
    appId: '1:942388891595:ios:af85919962a4cdc788304e',
    messagingSenderId: '942388891595',
    projectId: 'radar-grid-15e35',
    storageBucket: 'radar-grid-15e35.firebasestorage.app',
    iosBundleId: 'com.example.theRadarGrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKJdlMQVBFG8BTFBIH5istPEbTtLryEWA',
    appId: '1:942388891595:web:2f887764aa9a9ac288304e',
    messagingSenderId: '942388891595',
    projectId: 'radar-grid-15e35',
    authDomain: 'radar-grid-15e35.firebaseapp.com',
    storageBucket: 'radar-grid-15e35.firebasestorage.app',
    measurementId: 'G-TZXN9KXRS8',
  );
}
